### ISSUE TITLE
docs bayesfactor inclusion

### ISSUE THREAD

**Issue by strengejacke** [easystats/bayestestR#141]
I would change the wording:

> Inclusion Bayes factors answer the question: Given the observed data, how much more likely have models with a particular effect become, compared to models without that particular effect?

to

> Inclusion Bayes factors answer the question: Given the observed data, how much more likely are models with a particular effect, compared to models without that particular effect?

But in general, what is the reference for _likely_? More likely according to what? This sentence currently makes not much sense to me, or am I missing something?

**Comment by mattansb** [comment]
BFs are always a measure of comparative likelihood (P(Data|Model)).
So inclusion BFs compare P(Data|Models with Effect X) / P(Data|Models without Effect X).

I have gone over the vignette and made sure that all references to likelihoods and probabilities are correct (and have changed to something closer to what you suggested).

**Comment by strengejacke** [comment]
Yes, I know what is actually meant. But a model can't have the "natural property" of being "likely". I would say that, given the data, the model better fits to the data, so it's _more likely_ to _better_ fit (or describe) to the data (than the other model).

A model itself can't be likely.

**Comment by mattansb** [comment]
I think I understand - you think the concept of likelihood should be explained to the reader?

Do you think it would be enough to address this once in the beginning, like (the suggested addition is in bold):
> Bayes factors **indicate which of the compared models provided a better fit (or better describes) the observed data**, and are computed as the ratio of marginal likelihoods of two competing hypotheses / models, ...

**Comment by strengejacke** [comment]
Yes, I think this clearer. Although most people probably know what is meant, I think it is in general helpful to explicitely write where "more likely" refers to.

**Comment by mattansb** [comment]
Okay, let me know of any other changes you think are needed - happy to make things more clear (I've already got feedback from some colleagues and peers that our documentation is superb!)

**Comment by strengejacke** [comment]
Ups, sorry, I wasn't referring to the vignette, but rather to the .rd-file (from bayesfactor_inclusion.R) :-D
The vignette was very clear, I think, but you can keep the initial sentence there as wel...

my mistake...

**Comment by mattansb** [comment]
I'll keep the changes to the vignette nonetheless (I think they are a bit better now) 😃 

I think I addressed this issue in all the `.rd`s.

**Comment by strengejacke** [comment]
A but off-topic, but what I'm again thinking of:
I really like the implementation of the BF-stuff! I have the feeling that I'm probably starting to use BF more often in the future, or also include it for teaching. :-) 

Very cool contributions, Mattan, thanks a lot! (and probably also Dominique? I haven't followed all this work in detail...)

**Comment by mattansb** [comment]
Glad to! I really think that this package will make Bayesian modelling and inference easier to conduct (in the best way possible!)

**Comment by strengejacke** [comment]
May I re-open this issue, because it fits into the previous discussion... I have revised following sentence in the BF vignette:

> **Given the observed data, which model is more likely?**

into

> **Given the observed data, which model is more likely (to provide a better fit or to better describe the data)?**

Because I still don't get what "more likely" means, as there is no reference (i.e. nothing "more likely" refers to). Can't we make a similar statement as for inclusion BF? Here, it's quite clear what actually is compared and where the BF refers to:

> Given the observed data, how much more likely are models with a particular effect, compared to models without that particular effect?

**Comment by mattansb** [comment]
> Given the observed data, which model is more likely (to provide a better fit or to better describe the data)?

This seems very bulky... Not clear whats wrong with saying that a one model is more likely than another? Each model has (marginal) likelihood - the model with larger likelihood is more likely, no?

**Comment by mattansb** [comment]
Maybe:

> Which model is more likely (better describes the observed data)?

**Comment by mattansb** [comment]
Technically this should only be "which model has a higher marginal likelihood", and not quite "better describes the data" (as a model with a larger R<sup>2</sup> *can* have a smaller marginal likelihood do to the build-in penalty for over-complex models)... So maybe:

> Under which model is the observed data more likely?

**Comment by mattansb** [comment]
Technically this should only be "which model has a higher marginal likelihood", and not quite "better describes the data" (as a model with a larger R2 can have a smaller marginal likelihood due to the build-in penalty for over-complex models)... 

**The joint probability of the observed data under model A is the likelihood of the model given the observed data.** So I keep going back to:

> Which model is more likely, given the observed data?

**Comment by strengejacke** [comment]
My problem is to grasp, what a "likely model" is? And what would be an unlikely model? 

It's more clear in the sense of Bayes theorem, that, given the data, the probability of an effect is x%. But here the likelihood refers to an effect compared to no (or opposite) effect.

**Comment by strengejacke** [comment]
So, what does it mean when a model is "likely"? Likely a good model? Likely by random chance? Likely on Tuesdays? More likely, in the sense of what? Probably greater evidence (against something), but then we should name this something.

**Comment by strengejacke** [comment]
> Which model is more likely, given the observed data?

Maybe this is technically correct, but it _sounds_ to me that the model, with all its variables in it, has fallen from heaven and was not a result of a researcher's decisions and actions.

**Comment by mattansb** [comment]
A model is never likely - the whole point of BF is that a model is more (or less) likely than some *other* model.

When a model is more likely than another, it means that the data "looks" more like it is the result of the data generation process described by that model (and looks less like it is the result of the data generation process described by the other model).

**Comment by mattansb** [comment]
> ... but it sounds to me that the model, with all its variables in it, has fallen from heaven and was not a result of a researcher's decisions and actions.

Any model specified by a human / theory. Two models are specified and compared. These can be any two models - with different predictors, different priors for the same predictors, different link-functions, different nested structures... etc... The BF doesn't "care" where the model came from.

**Comment by strengejacke** [comment]
> When a model is more likely than another, it means that the data "looks" more like it is the result of the data generation process described by that model (and looks less like it is the result of the data generation process described by the other model).

I think this is the missing reference point, and what I wanted to describe with "better fit" or "describe the data". _Model A is more likely the result of the data generating process than Model B._ - this makes sense.

> The whole point of BF is that a model is more (or less) likely than some other model.

No, I don't think you can just compare models and then get a statement about likelihood. You always need to say _what_ (component, aspect, ...) is more likely, or from which action / process a model is a more likely result than another model. You can't make a statement about likelihood without this reference, as you already said: "A model is never likely".

So, although I know what is meant with the sentence (and I know what BF compute), I think the sentence _Given the observed data, which model is more likely?_ is more clear to a broader readership when we add something like "data generating process" or whatever.

**Comment by strengejacke** [comment]
(I know I have my nitpicking day today, forgive me) ;-)

**Comment by mattansb** [comment]
> I don't think you can just compare models and then get a statement about likelihood.

You can and do - because you're comparing the whole model's *marginal* likelihood (across all parameter space). This is why you can't really compute a BF for a single parameter / aspect - you're always comparing two *whole* models (the Savage-Dickey ratio, though computed based on a single model, is actually an approximation of the given model vs a similar model with that parameter fixed at 0 - so we're still comparing two whole models). This is one of the draw-backs of BFs - how non-specific they are (unlike p-values / ROPE / pd, etc - that can be computed per parameter).

If you want to refer to the "data generating process" in the BF definition, it would be:

> Which model is more likely to have generated the observed data?

I think this would be more confusing to novices compared to my original definition (which is more close to, of example Rouder et al. 2012: "Bayes factors describe the relative probability of data under
competing [models]" or Wagenmakers et al. 2010: "[the model] under which the observed data are [more probable]"). For most people, even if they don't have a complete grasp on what likelihood is, they have some sense of what relative-likelihoods are and what they mean (similar to likelihood ratio significance tests). Thus, I think in this case it is better to be more clear than more exact (["Lie-to-children"](https://en.wikipedia.org/wiki/Lie-to-children)), taking a page out of the general-audience BF papers who do the same.

(If today is you nitpicking day, does that mean that tomorrow there will be no nitpicking?? 😜)
(Also, nitpick away 😎 - it forces me to see if I actually *do* know what I'm talking about!)

**Comment by strengejacke** [comment]
> I think this would be more confusing to novices compared to my original definition (which is more close to, of example Rouder et al. 2012: "Bayes factors describe the relative probability of data under
competing [models]" or Wagenmakers et al. 2010: "[the model] under which the observed data are [more probable]"). 

I think this notion sounds somewhat reverse to what we have written in the vignette. It is the probability of the _data_, so the _data_ is more likely (not the model).

> > I don't think you can just compare models and then get a statement about likelihood.

> You can and do - because you're comparing the whole model's marginal likelihood (across all parameter space). 

Yes, yes, I know. But still it's a statement about the _data's_ or _data generating process's_ likelihood. I know (or I think) that this is meant with "Given the observed data, which model is more likely?", but when we stick close to your given definitions, it would be something like "Given the observed data, which model is more likely **to produce these data**"? This indeed sound somewhat strange, but why don't we use one of the above definitions? Something like, "Under which model are the observed data more likely"?

**Comment by mattansb** [comment]
(I think we're almost there...)

(I'm like 99.8% sure that) Data doesn't have likelihood - parameter space has likelihood (which is equal to the conditional probability of data on that parameter space, or course).
<br><br><br>
Anyway, I'm fine with adopting the definition by Rouder et al, as you suggested - maybe something like this (with a main definition, and the accompanying explanation?):
> > Under which model is the the observed data more probable?

> In other words, which model is more likely to have produce the observed data?

**Comment by strengejacke** [comment]
> Data doesn't have likelihood - parameter space has likelihood (which is equal to the conditional probability of data on that parameter space, or course.

True, that is most exactly.

**Comment by mattansb** [comment]
So it's settled?
If so, I'll make this change to the vignette (and look over the all other BF docs too, along with #166 ) tomorrow morning.

**Comment by strengejacke** [comment]
Yes! Feel free to close this now or after you changed the vignette.

**Comment by DominiqueMakowski** [comment]
> So, what does it mean when a model is "likely"? Likely a good model? Likely by random chance? Likely on Tuesdays? More likely, in the sense of what?

definitively likely on Tuesdays! 😂

> (I'm like 99.8% sure that) Data doesn't have likelihood

please say "I am 0.998 sure of that" otherwise you will awake the fury of @strengejacke 👀😁

**Comment by mattansb** [comment]
I'm resetting the dev branch (deleting and recreating) as there seems to be some problem with merging the master branch into dev 😒...
